version: 2

sources:
  - name: erp
    description: Fonte SAP da northwind
    schema: erp_northwind
    tables:
    - name: products
      columns:
        - name: product_id
          tests:
            - unique
            - not_null
    
    - name: categories
      columns:
        - name: category_id
          tests:
            - unique
            - not_null
        
    - name: suppliers
      columns:
        - name: supplier_id
          tests:
            - unique
            - not_null
        